In [19]:
from dotenv import load_dotenv
load_dotenv()

True

In [5]:
import os
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

import pandas as pd

In [6]:
books = pd.read_csv("books_cleaned.csv")
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [7]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [8]:
books["tagged_description"].to_csv("tagged_description.txt", index=False, header=False, sep="\n")

In [10]:
text_splitter = CharacterTextSplitter(separator="\n", chunk_size=1, chunk_overlap=0)
raw_documents = TextLoader("tagged_description.txt").load()
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1168, which is longer than the specified 1
Created a chunk of size 1214, which is longer than the specified 1
Created a chunk of size 373, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 483, which is longer than the specified 1
Created a chunk of size 482, which is longer than the specified 1
Created a chunk of size 960, which is longer than the specified 1
Created a chunk of size 188, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 296, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1
Created a chunk of size 881, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 1189, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 270, which is longer than the specified 1
Created a chunk of size 211, which is longer than the specified 1
Created a chunk of size 214, which is longer than the specified 1
Created a chunk of size 513, which is longer than the specified 1
Created a chunk of size 752, which is longer than the specified 1
Created a chunk of size 388, which is longer than the specified 1
Created a chunk of size 263, which is longer than the specified 1
Created a chunk of size 253, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 728, which is longer than the specified 1
Created a chunk of size 721, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 473, which is longer than the specified 1
Created a chunk of size 270, which is longer than the specified 1
Created a chunk of size 1267, which is longer than the specified 1
Created a chunk of size 681, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 553, which is longer than the specified 1
Created a chunk of size 521, which is longer than the specified 1
Created a chunk of size 280, which is longer than the specified 1
Created a chunk of size 787, which is longer than the specified 1
Created a chunk of size 564, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 177, which is longer than the specified 1
Created a chunk of size 297, which is longer than the specified 1
Created a chunk of size 533, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 563, which is longer than the specified 1
Created a chunk of size 385, which is longer than the specified 1
Created a chunk of size 410, which is longer than the specified 1
Created a chunk of size 461, which is longer than the specified 1
Created a chunk of size 595, which is longer than the specified 1
Created a chunk of size 476, which is longer than the specified 1
Created a chunk of size 459, which is longer than the specified 1
Created a chunk of size 257, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 614, which is longer than the specified 1
Created a chunk of size 419, which is longer than the specified 1
Created a chunk of size 887, which is longer than the specified 1
Created a chunk of size 693, which is longer than the specified 1
Created a chunk of size 302, which is longer than the specified 1
Created a chunk of size 217, which is longer than the specified 1
Created a chunk of size 277, which is longer than the specified 1
Created a chunk of size 2010, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 479, which is longer than the specified 1
Created a chunk of size 300, which is longer than the specified 1
Created a chunk of size 520, which is longer than the specified 1
Created a chunk of size 647, which is longer than the specified 1
Created a chunk of size 778, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 686, which is longer than the specified 1
Created a chunk of size 548, which is longer than the specified 1
Created a chunk of size 1225, which is longer than the specified 1
Created a chunk of size 406, which is longer than the specified 1
Created a chunk of size 1184, which is longer than the specified 1
Created a chunk of size 1214, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 1057, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 688, which is longer than the specified 1
Created a chunk of size 876, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 766, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 417, which is longer than the specified 1
Created a chunk of size 208, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 723, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 163, which is longer than the specified 1
Created a chunk of size 526, which is longer than the specified 1
Created a chunk of size 521, which is longer than the specified 1
Created a chunk of size 214, which is longer than the specified 1
Created a chunk of size 338, which is longer than the specified 1
Created a chunk of size 899, which is longer than the specified 1
Created a chunk of size 1270, which is longer than the specified 1
Created a chunk of size 558, which is longer than the specified 1
Created a chunk of size 1635, which is longer than the specified 1
Created a chunk of size 436, which is longer than the specified 1
Created a chunk of size 249, which is longer than the specified 1
Created a chunk of size 777, which is longer than the specified 1
Created a chunk of size 716, which is longer than the specified 1
Created a chunk of size 514, which is longer than the specified 1
Created a chunk of size 958, which is longer than the specified 1
Created a chunk of size 198, which is longer than the specified 1
Created a chunk of size 1132, which is longer than the specified 1
Created a chunk of size 168, which is longer than the specified 1
Created a chunk of size 1325, which is longer than the specified 1
Created a chunk of size 851, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 801, which is longer than the specified 1
Created a chunk of size 1119, which is longer than the specified 1
Created a chunk of size 836, which is longer than the specified 1
Created a chunk of size 260, which is longer than the specified 1
Created a chunk of size 235, which is longer than the specified 1
Created a chunk of size 732, which is longer than the specified 1
Created a chunk of size 1195, which is longer than the specified 1
Created a chunk of size 710, which is longer than the specified 1
Created a chunk of size 773, which is longer than the specified 1
Created a chunk of size 278, which is longer than the specified 1
Created a chunk of size 307, which is longer than the specified 1
Created a chunk of size 356, which is longer than the specified 1
Created a chunk of size 766, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 716, which is longer than the specified 1
Created a chunk of size 2012, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 1286, which is longer than the specified 1
Created a chunk of size 1231, which is longer than the specified 1
Created a chunk of size 729, which is longer than the specified 1
Created a chunk of size 750, which is longer than the specified 1
Created a chunk of size 445, which is longer than the specified 1
Created a chunk of size 1242, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 912, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 844, which is longer than the specified 1
Created a chunk of size 1126, which is longer than the specified 1
Created a chunk of size 1073, which is longer than the specified 1
Created a chunk of size 1318, which is longer than the specified 1
Created a chunk of size 361, which is longer than the specified 1
Created a chunk of size 2834, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 240, which is longer than the specified 1
Created a chunk of size 171, which is longer than the specified 1
Created a chunk of size 204, which is longer than the specified 1
Created a chunk of size 570, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 1141, which is longer than the specified 1
Created a chunk of size 1004, which is longer than the specified 1
Created a chunk of size 715, which is longer than the specified 1
Created a chunk of size 710, which is longer than the specified 1
Created a chunk of size 2510, which is longer than the specified 1
Created a chunk of size 954, which is longer than the specified 1
Created a chunk of size 307, which is longer than the specified 1
Created a chunk of size 351, which is longer than the specified 1
Created a chunk of size 639, which is longer than the specified 1
Created a chunk of size 405, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 793, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 254, which is longer than the specified 1
Created a chunk of size 1422, which is longer than the specified 1
Created a chunk of size 1083, which is longer than the specified 1
Created a chunk of size 1144, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 790, which is longer than the specified 1
Created a chunk of size 297, which is longer than the specified 1
Created a chunk of size 1086, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 876, which is longer than the specified 1
Created a chunk of size 806, which is longer than the specified 1
Created a chunk of size 1812, which is longer than the specified 1
Created a chunk of size 1830, which is longer than the specified 1
Created a chunk of size 1064, which is longer than the specified 1
Created a chunk of size 955, which is longer than the specified 1
Created a chunk of size 1180, which is longer than the specified 1
Created a chunk of size 281, which is longer than the specified 1
Created a chunk of size 281, which is longer than the specified 1
Created a chunk of size 286, which is longer than the specified 1
Created a chunk of size 1284, which is longer than the specified 1
Created a chunk of size 1642, which is longer than the specified 1
Created a chunk of size 757, which is longer than the specified 1
Created a chunk of size 1930, which is longer than the specified 1
Created a chunk of size 872, which is longer than the specified 1
Created a chunk of size 2008, which is longer than the specified 1
Created a chunk of size 2285, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 1003, which is longer than the specified 1
Created a chunk of size 577, which is longer than the specified 1
Created a chunk of size 288, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 1142, which is longer than the specified 1
Created a chunk of size 557, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 1086, which is longer than the specified 1
Created a chunk of size 1483, which is longer than the specified 1
Created a chunk of size 221, which is longer than the specified 1
Created a chunk of size 1135, which is longer than the specified 1
Created a chunk of size 722, which is longer than the specified 1
Created a chunk of size 668, which is longer than the specified 1
Created a chunk of size 765, which is longer than the specified 1
Created a chunk of size 606, which is longer than the specified 1
Created a chunk of size 570, which is longer than the specified 1
Created a chunk of size 965, which is longer than the specified 1
Created a chunk of size 857, which is longer than the specified 1
Created a chunk of size 1032, which is longer than the specified 1
Created a chunk of size 189, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 495, which is longer than the specified 1
Created a chunk of size 652, which is longer than the specified 1
Created a chunk of size 348, which is longer than the specified 1
Created a chunk of size 733, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 1015, which is longer than the specified 1
Created a chunk of size 970, which is longer than the specified 1
Created a chunk of size 204, which is longer than the specified 1
Created a chunk of size 688, which is longer than the specified 1
Created a chunk of size 544, which is longer than the specified 1
Created a chunk of size 242, which is longer than the specified 1
Created a chunk of size 207, which is longer than the specified 1
Created a chunk of size 376, which is longer than the specified 1
Created a chunk of size 931, which is longer than the specified 1
Created a chunk of size 564, which is longer than the specified 1
Created a chunk of size 854, which is longer than the specified 1
Created a chunk of size 715, which is longer than the specified 1
Created a chunk of size 749, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 324, which is longer than the specified 1
Created a chunk of size 241, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 723, which is longer than the specified 1
Created a chunk of size 245, which is longer than the specified 1
Created a chunk of size 227, which is longer than the specified 1
Created a chunk of size 704, which is longer than the specified 1
Created a chunk of size 1912, which is longer than the specified 1
Created a chunk of size 395, which is longer than the specified 1
Created a chunk of size 485, which is longer than the specified 1
Created a chunk of size 622, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 556, which is longer than the specified 1
Created a chunk of size 386, which is longer than the specified 1
Created a chunk of size 229, which is longer than the specified 1
Created a chunk of size 425, which is longer than the specified 1
Created a chunk of size 418, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 166, which is longer than the specified 1
Created a chunk of size 624, which is longer than the specified 1
Created a chunk of size 2616, which is longer than the specified 1
Created a chunk of size 1580, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 994, which is longer than the specified 1
Created a chunk of size 847, which is longer than the specified 1
Created a chunk of size 263, which is longer than the specified 1
Created a chunk of size 336, which is longer than the specified 1
Created a chunk of size 1530, which is longer than the specified 1
Created a chunk of size 213, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 2030, which is longer than the specified 1
Created a chunk of size 396, which is longer than the specified 1
Created a chunk of size 1619, which is longer than the specified 1
Created a chunk of size 698, which is longer than the specified 1
Created a chunk of size 822, which is longer than the specified 1
Created a chunk of size 354, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 1189, which is longer than the specified 1
Created a chunk of size 195, which is longer than the specified 1
Created a chunk of size 508, which is longer than the specified 1
Created a chunk of size 663, which is longer than the specified 1
Created a chunk of size 1282, which is longer than the specified 1
Created a chunk of size 260, which is longer than the specified 1
Created a chunk of size 242, which is longer than the specified 1
Created a chunk of size 215, which is longer than the specified 1
Created a chunk of size 198, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 1277, which is longer than the specified 1
Created a chunk of size 198, which is longer than the specified 1
Created a chunk of size 1056, which is longer than the specified 1
Created a chunk of size 378, which is longer than the specified 1
Created a chunk of size 269, which is longer than the specified 1
Created a chunk of size 177, which is longer than the specified 1
Created a chunk of size 225, which is longer than the specified 1
Created a chunk of size 222, which is longer than the specified 1
Created a chunk of size 784, which is longer than the specified 1
Created a chunk of size 969, which is longer than the specified 1
Created a chunk of size 613, which is longer than the specified 1
Created a chunk of size 163, which is longer than the specified 1
Created a chunk of size 757, which is longer than the specified 1
Created a chunk of size 289, which is longer than the specified 1
Created a chunk of size 245, which is longer than the specified 1
Created a chunk of size 963, which is longer than the specified 1
Created a chunk of size 232, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 786, which is longer than the specified 1
Created a chunk of size 648, which is longer than the specified 1
Created a chunk of size 984, which is longer than the specified 1
Created a chunk of size 799, which is longer than the specified 1
Created a chunk of size 193, which is longer than the specified 1
Created a chunk of size 1163, which is longer than the specified 1
Created a chunk of size 253, which is longer than the specified 1
Created a chunk of size 203, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1

In [16]:
documents[5]

Document(metadata={'source': 'tagged_description.txt'}, page_content="9780006380832 Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall's history of the exploration and exploitation by Chinese and Arab travellers, and by the Portuguese, Dutch and British alike is one of brutality, betrayal and colonial ambition.")

In [39]:
persist_directory = "db_books_store"
db_books = Chroma.from_documents(documents=documents, embedding=OpenAIEmbeddings(), persist_directory=persist_directory)

In [41]:
query = "A book about children"
docs = db_books.similarity_search(query=query, k=15)
docs

[Document(id='7fbec08e-22c8-4e94-a572-253f2a4cba34', metadata={'source': 'tagged_description.txt'}, page_content='9780786812912 In her first illustrated book for children, the Pulitzer Prize–winning author Toni Morrison introduces three feisty children who show grown-ups what it really means to be a kid.'),
 Document(id='45fe5e6f-25ca-4e29-84f0-e6a9a47ee044', metadata={'source': 'tagged_description.txt'}, page_content='9780140621624 When their father is sent away to prison, three London children move to the country where they keep busy preventing accidents on the nearby railway, making many new friends, and generally learning a good deal about themselves.'),
 Document(id='14078105-79c0-47b7-895e-91274a1c1f63', metadata={'source': 'tagged_description.txt'}, page_content='9780374528539 A lighthearted but insightful guide to raising adolescent children shows parents how to deal with teenagers living in a faster-paced, less morally certain world than the one they knew. Original. 50,000 first printing.'),
 Document(id='211d237e-0f70-4a93-9b07-23226bd4ce2a', metadata={'source': 'tagged_description.txt'}, page_content="9780679847595 In a classic children's story, three unsinkable orphans, believing that they are destined for greatness, set out to make their marks in the world of show business. Reprint."),
 Document(id='1ff26eae-19de-4017-a9a1-16bd3c0d80ed', metadata={'source': 'tagged_description.txt'}, page_content="9780941807555 THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wonderful resource for parents looking to introduce their children to the wisdom and beauty of Christian faith. Illustrated with early twentieth-century art from artists such as Jessie Wilcox Smith, Ellen H. Clapsaddle, and Maud and Miska Petersham, this Little Big Book presents selected bible stories, parables, and verses; poems and prayers; excerpts and fables; songs and hymns; and activities - all collected in one delightful volume. A celebration of God's enduring message of love, GOD'S CHILDREN is sure to provide an endless wellspring of inspiration and hope."),
 Document(id='5b5408c7-a6de-4ea4-a9b9-7e98c1f847f3', metadata={'source': 'tagged_description.txt'}, page_content="9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='f4e02900-a638-4982-814f-543daf161206', metadata={'source': 'tagged_description.txt'}, page_content='9780440362050 A small boy finds excitement and promise in the daily life of his California valley during the early years of the twentieth century in this collection of short stories'),
 Document(id='071adc1c-f16b-47ef-b99e-65299cfa1e82', metadata={'source': 'tagged_description.txt'}, page_content="9780571207565 Three classic children's stories, Mrs Cherry's Kitchen, The Bed Book and The It Doesn't Matter Suit, collected together in one volume for the first time."),
 Document(id='28255834-535a-4fbd-89c2-cf4a28c87794', metadata={'source': 'tagged_description.txt'}, page_content='9780140503449 The noisy children of three neighboring families have a gay time at Christmas baking cookies, cutting and decorating trees, eating fruitcake and tarts, and opening Christmas gifts.'),
 Document(id='a35c26af-dd37-4e17-b3ea-ae3b8bcc976f', metadata={'source': 'tagged_description.txt'}, page_content="9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."),
 Document(id='7c1604c8-ea1c-4b9c-b24c-29fc9330dfe5', metadata={'source': 'tagged_description.txt'}, page_content="9780590032490 A young boy and his Norwegian grandmother, who is an expert on witches, together foil a witches' plot to destroy the world's children by turning them into mice."),
 Document(id='5e287e30-adcc-47a3-b095-928aaa1c080a', metadata={'source': 'tagged_description.txt'}, page_content='9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.'),
 Document(id='5e8279a5-5109-4388-aca5-93c293a8d95b', metadata={'source': 'tagged_description.txt'}, page_content="9780241003008 Eric Carle's children's classic is the story of a very small and very hungry caterpillar who manages to nibble his way through the pages of this enchanting book."),
 Document(id='79a92698-ed87-4b39-977b-28833ce820cd', metadata={'source': 'tagged_description.txt'}, page_content="9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."),
 Document(id='b1a1c519-ad39-4d1e-8466-e8fe0ab9aba9', metadata={'source': 'tagged_description.txt'}, page_content='9781590171240 In post-World War II London, two street-tough children attempt to build a hidden garden, an act that awakens hidden courage in the children and profoundly disrupts the neighborhood.')]

In [ ]:
# db_books.delete_collection()

In [43]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."

In [48]:
docs[0].page_content.split()[0]

'9780786812912'

In [51]:
books[books["isbn13"] == int(docs[0].page_content.split()[0])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3760,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,The Big Box,9780786812912 In her first illustrated book fo...

In [65]:
def retrieve_semantic_recommendations(query: str, tok_k: int = 10, k:int=10) -> pd.DataFrame:
    recs = db_books.similarity_search(query=query, k=k)
    ids = [int(rec.page_content.split()[0]) for rec in recs]
    return books[books["isbn13"].isin(ids[:tok_k])]

In [66]:
retrieve_semantic_recommendations("a book about children", k=50)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
711,9780140621624,0140621628,The Railway Children,E. Nesbit,Fiction,http://books.google.com/books/content?id=fFesd...,"When their father is sent away to prison, thre...",1995.0,4.00,212.0,178.0,The Railway Children,9780140621624 When their father is sent away t...
1652,9780374528539,0374528535,"Get Out of My Life, But First Could You Drive ...",Anthony E. Wolf,Family & Relationships,http://books.google.com/books/content?id=oKdbC...,A lighthearted but insightful guide to raising...,2002.0,3.94,240.0,1301.0,"Get Out of My Life, But First Could You Drive ...",9780374528539 A lighthearted but insightful gu...
2201,9780440362050,0440362059,My Name is Aram,William Saroyan,Fiction,http://books.google.com/books/content?id=2P3XA...,A small boy finds excitement and promise in th...,1966.0,4.15,151.0,975.0,My Name is Aram,9780440362050 A small boy finds excitement and...
2827,9780571207565,0571207561,Collected Children's Stories,Sylvia Plath,"Children's poetry, American",http://books.google.com/books/content?id=i6oCG...,"Three classic children's stories, Mrs Cherry's...",2001.0,4.22,54.0,111.0,Collected Children's Stories,9780571207565 Three classic children's stories...
3130,9780679847595,0679847596,Ballet Shoes,Noel Streatfeild,Juvenile Fiction,http://books.google.com/books/content?id=0UvIa...,"In a classic children's story, three unsinkabl...",1993.0,4.07,233.0,28222.0,Ballet Shoes,"9780679847595 In a classic children's story, t..."
3748,9780786808373,0786808373,Baby Einstein: Birds,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=0jxHP...,"Introducing your baby to birds, cats, dogs, an...",2002.0,3.78,20.0,9.0,Baby Einstein: Birds,"9780786808373 Introducing your baby to birds, ..."
3749,9780786808380,0786808381,Baby Einstein: Babies,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=jv4NA...,"Introduce your babies to birds, cats, dogs, an...",2002.0,4.03,20.0,29.0,Baby Einstein: Babies,"9780786808380 Introduce your babies to birds, ..."
3750,9780786808397,078680839X,Baby Einstein: Dogs,Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=qut8t...,"Introduce your baby to birds, cats, dogs, and ...",2002.0,3.81,20.0,26.0,Baby Einstein: Dogs,"9780786808397 Introduce your baby to birds, ca..."
3760,9780786812912,0786812915,The Big Box,Toni Morrison;Slade Morrison,Juvenile Fiction,http://books.google.com/books/content?id=LyYKA...,"In her first illustrated book for children, th...",2002.0,3.95,48.0,375.0,The Big Box,9780786812912 In her first illustrated book fo...
4264,9780941807555,094180755X,The Little Big Book for God's Children,Lena Tabori;Alice Wong,Religion,http://books.google.com/books/content?id=s2PfT...,THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wo...,2001.0,4.88,352.0,8.0,The Little Big Book for God's Children,9780941807555 THE LITTLE BIG BOOK FOR GOD'S CH...